#pragma once
void testTelefon();
void testSerie();
void testDrona();
void testRepoTemplate();
void testService();
void testRepoFileCSV();
void testRepoFileHTML();
void testRepoFileSerie();
void tests();